version: 2

project_name: ipstream

changelog:
  use: github

report_sizes: true

checksum:
  name_template: checksums.txt
  algorithm: sha256

upx:
  - ids:
      - ipstream
    enabled: true
    compress: best
    lzma: true

builds:
  - id: ipstream
    main: ./cmd/ipstream
    binary: ipstream
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.gitCommit={{.ShortCommit}} -X main.buildDate={{.Date}}

archives:
  - id: ipstream
    ids:
      - ipstream
    files:
      - README.md
      - LICENSE
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

nfpms:
  - id: ipstream
    ids:
      - ipstream
    package_name: ipstream
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Kiba Amor
    homepage: https://github.com/kibaamor/ipstream
    maintainer: Kiba Amor <kibaamor@users.noreply.github.com>
    description: Extract IPv4 and IPv6 addresses from byte streams.
    license: Apache-2.0
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    section: utils
    priority: optional

homebrew_casks:
  - name: ipstream
    ids:
      - ipstream
    binaries:
      - ipstream
    homepage: https://github.com/kibaamor/ipstream
    description: Extract IPv4 and IPv6 addresses from byte streams.
    license: Apache-2.0
    repository:
      owner: kibaamor
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_PUBLISH_TOKEN }}"
    commit_msg_template: "ipstream cask: {{ .Tag }}"

scoops:
  - name: ipstream
    ids:
      - ipstream
    homepage: https://github.com/kibaamor/ipstream
    description: Extract IPv4 and IPv6 addresses from byte streams.
    license: Apache-2.0
    repository:
      owner: kibaamor
      name: scoop-bucket
      token: "{{ .Env.GORELEASER_PUBLISH_TOKEN }}"
    commit_msg_template: "ipstream: {{ .Tag }}"

dockers_v2:
  - id: ipstream
    ids:
      - ipstream
    dockerfile: Dockerfile
    images:
      - ghcr.io/kibaamor/ipstream
    tags:
      - "{{.Version}}"
      - "{{.Major}}.{{.Minor}}"
      - "{{.Major}}"
      - latest
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.description: Extract IPv4 and IPv6 addresses from byte streams.
      org.opencontainers.image.licenses: Apache-2.0
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.source: https://github.com/kibaamor/ipstream
      org.opencontainers.image.title: ipstream
      org.opencontainers.image.url: https://github.com/kibaamor/ipstream
      org.opencontainers.image.version: "{{ .Version }}"
