name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: "stable"

      - name: Vet
        run: go vet ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

      - name: Test
        run: go clean -testcache && go test -tags='ipstreamtests ipstreamstats' -covermode=atomic -coverprofile coverage.out ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: coverage.out
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
